import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import Background from "./components/Background";
import React from "react";
import Graphic from "../public/Graphic.svg";
import Footer from "./components/Footer";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scientistx Technology",
  description: "Generated by create next app",
};
const style = {
  canvas: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "0px",
    left: "0px",
    backgroundImage: "url(" + Graphic + ")",
    backgroundSize: "cover",
    zIndex: -1,
    color: "#ffff",
    backgroundColor: "#f7f7f74f",
  },
};
export default function RootLayout({ children, page }) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#333333" }} className={inter.className}>
        <Background />
        <Providers>
          <div>
            <Header />
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
