"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Parallax, ParallaxLayer } from "@react-spring/parallax";
import Footer from "./components/Footer";
import { useRef } from "react";
import ParticlesBg from "particles-bg";
import Graphic from '../public/Graphic.svg'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Scientistx Technology",
//   description: "Generated by create next app",
// };
const style = {
  canvas: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "0px",
    left: "0px",
    backgroundImage: "url(" + Graphic + ")",
    backgroundSize: "cover",
    zIndex: -1,
    color: "#ffff",
    backgroundColor:"#f7f7f74f"
  }
};
export default function RootLayout({ children }) {
  const parallaxRef = useRef();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <ParticlesBg type="lines" num={10} bg={style.canvas} />
          <Header />
          <Parallax
            ref={parallaxRef}
            pages={4}
            style={{ top: "0", left: "0" }}
          >
            {children}
            
          </Parallax>
          {/* <Footer /> */}
          {/* <BottomDrawer open={open} setOpen={setOpen} /> */}
        </div>
      </body>
    </html>
  );
}
