"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import Footer from "./components/Footer";
import React, { useEffect, useRef, useState } from "react";
import ParticlesBg from "particles-bg";
import Graphic from "../public/Graphic.svg";
import { useMediaQuery } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Scientistx Technology",
//   description: "Generated by create next app",
// };
const style = {
  canvas: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "0px",
    left: "0px",
    backgroundImage: "url(" + Graphic + ")",
    backgroundSize: "cover",
    zIndex: -1,
    color: "#ffff",
    backgroundColor: "#f7f7f74f",
  },
};
export default function RootLayout({ children, page }) {
  const [open, setOpen] = useState(false);
  const [header, setHeader] = React.useState(true);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ParticlesBg type="lines" num={10} bg={style.canvas} />
        <div className="">
          <Header header={header} open={open} setOpen={setOpen} />
          {children}
        </div>
      </body>
    </html>
  );
}
