
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";


import React from "react";
import Graphic from "../public/Graphic.svg";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Scientistx Technology",
  description: "Generated by create next app",
};
const style = {
  canvas: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "0px",
    left: "0px",
    backgroundImage: "url(" + Graphic + ")",
    backgroundSize: "cover",
    zIndex: -1,
    color: "#ffff",
    backgroundColor: "#f7f7f74f",
  },
};
export default function RootLayout({ children, page }) {

  return (
    <html lang="en">
      <body style={{backgroundColor:"#333333"}} className={inter.className}>
        {/* <ParticlesBg type="lines" num={10} bg={style.canvas} /> */}
        <div className="">
          <Header  />
          {children}
        </div>
      </body>
    </html>
  );
}
